import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    domains: [
      'placehold.co',
      'images.unsplash.com',
      'picsum.photos',
      'media.istockphoto.com',
      'img.freepik.com',
      'sukhis.com',
      'wallpapers.com',
      'tse1.mm.bing.net',
      'tse2.mm.bing.net',
      'tse3.mm.bing.net',
      'tse4.mm.bing.net',
      'www.tasteofhome.com',
      'palatesdesire.com',
      'www.cubesnjuliennes.com',
      'i0.wp.com',
      'www.awesomecuisine.com',
      'assets.vogue.com',
      'feeds.abplive.com',
      'tildaricelive.s3.eu-central-1.amazonaws.com',
      'clubmahindra.gumlet.io',
      'images7.alphacoders.com',
      'sifu.unileversolutions.com',
      'oventales.com',
      'www.healthifyme.com',
      'i.pinimg.com',
      'www.cookingcarnival.com',
      'farm9.staticflickr.com',
      'www.licious.in',
      'www.indianhealthyrecipes.com',
      'www.sandyathome.com',
      'vanitascorner.com',
      'media.30seconds.com',
      'i.ytimg.com',
      'www.vegrecipesofindia.com',
      'aromacookbook.files.wordpress.com',
      'as2.ftcdn.net',
      'www.flavourstreat.com',
      'images.squarespace-cdn.com',
      'content.thriveglobal.com',
      'www.krumpli.co.uk',
      'bonmasala.com',
      'hungryforever.net',
      'www.whiskaffair.com',
      'www.spiceindiaonline.com',
      'easychickenrecipes.com',
      'gomathirecipes.com',
      'tomatoblues.com',
      '3.bp.blogspot.com',
      'www.foodandwine.com',
      'www.masalakorb.com',
      'thestayathomechef.com',
      'cdn3.foodviva.com',
      'www.kannammacooks.com',
      'cdn.pixabay.com',
      'www.foodie-trail.com',
      'deliciouslittlebites.com',
      'cdn.sixtyandme.com',
      'food-fanatic-res.cloudinary.com',
      'findit-resources.s3.amazonaws.com',
      'm.media-amazon.com',
      'thebigmansworld.com',
    ],
  },
};

export default nextConfig;
