
import type {NextConfig} from 'next';

const nextConfig: NextConfig = {
  /* config options here */
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'placehold.co' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
      { protocol: 'https', hostname: 'picsum.photos' },
      { protocol: 'https', hostname: 'media.istockphoto.com' },
      { protocol: 'https', hostname: 'img.freepik.com' },
      { protocol: 'https', hostname: 'sukhis.com' },
      { protocol: 'https', hostname: 'wallpapers.com' },
      { protocol: 'https', hostname: '*.bing.net' },
      { protocol: 'https', hostname: 'www.tasteofhome.com' },
      { protocol: 'https', hostname: 'palatesdesire.com' },
      { protocol: 'https', hostname: 'www.cubesnjuliennes.com' },
      { protocol: 'https', hostname: 'i0.wp.com' },
      { protocol: 'https', hostname: 'www.awesomecuisine.com' },
      { protocol: 'https', hostname: 'assets.vogue.com' },
      { protocol: 'https', hostname: 'feeds.abplive.com' },
      { protocol: 'https', hostname: '*.amazonaws.com' },
      { protocol: 'https', hostname: 'clubmahindra.gumlet.io' },
      { protocol: 'https', hostname: 'images7.alphacoders.com' },
      { protocol: 'https', hostname: 'sifu.unileversolutions.com' },
      { protocol: 'https', hostname: 'oventales.com' },
      { protocol: 'https', hostname: 'www.healthifyme.com' },
      { protocol: 'https', hostname: 'i.pinimg.com' },
      { protocol: 'https', hostname: 'www.cookingcarnival.com' },
      { protocol: 'https', hostname: '*.staticflickr.com' },
      { protocol: 'https', hostname: 'www.licious.in' },
      { protocol: 'https', hostname: 'www.indianhealthyrecipes.com' },
      { protocol: 'https', hostname: 'www.sandyathome.com' },
      { protocol: 'https', hostname: 'vanitascorner.com' },
      { protocol: 'https', hostname: 'media.30seconds.com' },
      { protocol: 'https', hostname: 'i.ytimg.com' },
      { protocol: 'https', hostname: 'www.vegrecipesofindia.com' },
      { protocol: 'https', hostname: 'aromacookbook.files.wordpress.com' },
      { protocol: 'https', hostname: 'as2.ftcdn.net' },
      { protocol: 'https', hostname: 'www.flavourstreat.com' },
      { protocol: 'https', hostname: 'images.squarespace-cdn.com' },
      { protocol: 'https', hostname: 'content.thriveglobal.com' },
      { protocol: 'https', hostname: 'www.krumpli.co.uk' },
      { protocol: 'https', hostname: 'bonmasala.com' },
      { protocol: 'https', hostname: 'hungryforever.net' },
      { protocol: 'https', hostname: 'www.whiskaffair.com' },
      { protocol: 'https', hostname: 'www.spiceindiaonline.com' },
      { protocol: 'https', hostname: 'easychickenrecipes.com' },
      { protocol: 'https', hostname: 'gomathirecipes.com' },
      { protocol: 'http', hostname: 'tomatoblues.com' },
      { protocol: 'https', hostname: 'www.foodandwine.com' },
      { protocol: 'http', hostname: '*.blogspot.com' },
      { protocol: 'https', hostname: 'www.masalakorb.com' },
      { protocol: 'https', hostname: 'thestayathomechef.com' },
      { protocol: 'https', hostname: 'cdn3.foodviva.com' },
      { protocol: 'https', hostname: 'www.kannammacooks.com' },
      { protocol: 'https', hostname: 'www.foodie-trail.com' },
      { protocol: 'https', hostname: 'deliciouslittlebites.com' },
      { protocol: 'https', hostname: 'food-fanatic-res.cloudinary.com' },
      { protocol: 'https', hostname: 'm.media-amazon.com' },
      { protocol: 'https', hostname: 'thebigmansworld.com' },
      { protocol: 'https', hostname: 'cdn.pixabay.com' },
    ],
  },
};

export default nextConfig;
